import Head from 'next/head';
import { useState } from 'react';
import Message from '../components/comm/Message';
import User from '../components/comm/User';
export default function Home() {
    const [conversationId, setConversationId] = useState(1);
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="flex h-[calc(100vh-80px)] bg-white shadowHeader">
                    <div className="w-[300px]">
                        <User
                            conversationId={conversationId}
                            setConversationId={setConversationId}
                        />
                    </div>
                    <div className="flex-1">
                        <Message conversationId={conversationId} />
                    </div>
                </div>
            </main>
        </div>
    );
}
